### ISSUE TITLE
Plug-in is missing some images.

### ISSUE THREAD

**Issue by boggodan** [penman/browser-soundtrack-client#1]
This is a great little plug-in and probably my favorite hack from the MHD. 

There is one tiny issue - loading the plug-in folder as it is now fails because it's missing 3 images. I had to make them myself and it worked, but it would be easier for people to use the plug-in if the logo images were provided.

Cheers!

**Comment by alyssais** [comment]
Oh yeah, forgot to add those to the GitHub repo, sorry. I'll add them soon
